// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbfgxmuvttfqsrmvjqqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZmd4bXV2dHRmcXNybXZqcXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTc1OTcsImV4cCI6MjA2Mjk5MzU5N30.05AhFTxfqNOm_ZaVnUdtq0ChVnYitJZO5UKGQJOldrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);